### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken Pipe

### ISSUE THREAD

**Issue by phantomsom** [AirtestProject/iOS-Tagent#57]
My MacOs Version : macOS Mojave Version 10.14.4, iMac (21.5-inch, Late 2012)
My iOS device : iOS Version 12.2, iPad Pro (12.9 Inch, 3rd Generation)
My Xcode Version : Version 10.2.1

When running the project, I get this error, even though I can see airtestIDE connected to my iOS device. 

![image](https://user-images.githubusercontent.com/19833754/57365718-334b3a00-71b8-11e9-95d5-3b316f08d63e.png)

Here is line 30 in selftcp.py,
![image](https://user-images.githubusercontent.com/19833754/57366189-1400dc80-71b9-11e9-80b0-28c669a13e8b.png)

**Comment by EraChen233** [comment]
What's the output for iproxy terminal and Xcode?

**Comment by phantomsom** [comment]
iProxy terminal output 
![image](https://user-images.githubusercontent.com/19833754/57367040-d8671200-71ba-11e9-973d-913a38c64c42.png)

Xcode output
![image](https://user-images.githubusercontent.com/19833754/57367170-12381880-71bb-11e9-9273-065b954fe4bf.png)

**Comment by EraChen233** [comment]
Iproxy lost connection to your iPhone which leads to error `BrokenPipeError`.
I am sorry but iOS-Tangent is unstable recently.
We are working hard to fix this problem.  Please pay attention.

**Comment by rere332** [comment]
> Iproxy lost connection to your iPhone which leads to error `BrokenPipeError`.
> I am sorry but iOS-Tangent is unstable recently.
> We are working hard to fix this problem. Please pay attention.

same issue ,pls help to fix it ASAP, thanks!!!

**Comment by EraChen233** [comment]
I am sorry but iOS-Tagent does not support xcode> 10.2 yet.
Try downloading an older version of xcode at https://developer.apple.com/xcode/downloads.
The development work has been completed. It will be released as long as it fully tested. This won't take too long.

**Comment by EraChen233** [comment]
@phantomsom @rere332 

We have released a new version. Update the latest iOS-Tagent and you will be able to test latest iOS with to test latest Xcode.

**Comment by phantomsom** [comment]
> @phantomsom @rere332
> 
> We have released a new version. Update the latest iOS-Tagent and you will be able to test latest iOS with to test latest Xcode.

That's good, thanks for notifying me. Does that mean the [Errno 32] Broken Pipe issue has been fixed? I'm still getting the problem, running on Airtest v1.2.1.

My MacOs Version : macOS Mojave Version 10.14.4, iMac (21.5-inch, Late 2012)
My iOS device : iOS Version 12.2, iPad Pro (12.9 Inch, 3rd Generation)
My Xcode Version : Version 10.2.1

![image](https://user-images.githubusercontent.com/19833754/61102755-c7c86600-a4a1-11e9-86b0-99a1b6f15107.png)

**Comment by phantomsom** [comment]
More error messages, hope it helps:
![image](https://user-images.githubusercontent.com/19833754/61102888-6785f400-a4a2-11e9-88f7-e4dca5308321.png)

![image](https://user-images.githubusercontent.com/19833754/61102910-7f5d7800-a4a2-11e9-99df-db7b0d12cc1a.png)
